apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: my-long-lived-token
  annotations:
    kubernetes.io/service-account.name: my-serviceaccount   # This should match the name of the ServiceAccount defined in service-account.yml